// .claude/skills/krypton-design/ui_kits/storefront/Navbar.jsx
// Krypton storefront — top navigation bar.
function KrNavbar({ route, onNavigate, cartCount, query, onQuery, onSearch, user, onLogout }) {
  const { IconButton } = window.KryptonDesignSystem_457463;
  const link = (label, to) => {
    const active = route.name === to;
    return (
      <button
        onClick={() => onNavigate({ name: to })}
        style={{
          background: "none", border: "none", cursor: "pointer",
          fontFamily: "var(--font-sans)", fontSize: 15, fontWeight: active ? 700 : 500,
          color: active ? "var(--color-brand)" : "var(--text-body)",
          padding: "6px 2px", position: "relative",
        }}
      >
        {label}
        {active && <span style={{ position: "absolute", left: 0, right: 0, bottom: -2, height: 3, borderRadius: 3, background: "var(--color-accent)" }} />}
      </button>
    );
  };

  return (
    <header style={{
      position: "sticky", top: 0, zIndex: 50, height: "var(--navbar-h)",
      background: "rgba(255,255,255,0.88)", backdropFilter: "blur(10px)",
      borderBottom: "1px solid var(--border-subtle)",
      display: "flex", alignItems: "center", gap: 24,
      padding: "0 28px",
    }}>
      <img
        src="../../assets/logo/Krypton-navy.svg"
        alt="Krypton" style={{ height: 26, cursor: "pointer" }}
        onClick={() => onNavigate({ name: "home" })}
      />

      <nav style={{ display: "flex", gap: 22, marginLeft: 8 }}>
        {link("Inicio", "home")}
        {link("Catálogo", "catalog")}
      </nav>

      {/* Search */}
      <form
        onSubmit={(e) => { e.preventDefault(); onSearch(); }}
        style={{ flex: 1, maxWidth: 460, marginLeft: "auto", display: "flex", alignItems: "center", gap: 8,
          background: "var(--surface-sunken)", border: "1px solid var(--border-subtle)",
          borderRadius: 999, padding: "0 6px 0 14px", height: 42 }}
      >
        <i data-lucide="search" style={{ width: 18, height: 18, color: "var(--text-muted)" }} />
        <input
          value={query}
          onChange={(e) => onQuery(e.target.value)}
          placeholder="Buscar laptops, audio, componentes…"
          style={{ flex: 1, border: "none", outline: "none", background: "transparent",
            fontFamily: "var(--font-sans)", fontSize: 14, color: "var(--text-strong)" }}
        />
        <IconButton icon="arrow-right" label="Buscar" variant="solid" size="sm" round />
      </form>

      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        {user ? (
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span style={{ fontSize: 13, color: "var(--text-muted)", maxWidth: 130, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{user.email}</span>
            <IconButton icon="log-out" label="Cerrar sesión" variant="ghost" onClick={onLogout} />
          </div>
        ) : (
          <IconButton icon="user" label="Iniciar sesión" variant="outline" onClick={() => onNavigate({ name: "login" })} />
        )}
        <div style={{ position: "relative" }}>
          <IconButton icon="shopping-cart" label="Carrito" variant="cta" onClick={() => onNavigate({ name: "cart" })} />
          {cartCount > 0 && (
            <span style={{ position: "absolute", top: -5, right: -5, minWidth: 19, height: 19, padding: "0 5px",
              borderRadius: 999, background: "var(--kr-navy-800)", color: "#fff", fontSize: 11, fontWeight: 700,
              display: "flex", alignItems: "center", justifyContent: "center", border: "2px solid #fff" }}>{cartCount}</span>
          )}
        </div>
      </div>
    </header>
  );
}
window.KrNavbar = KrNavbar;

// frontend/src/app/layout/navbar/navbar.component.ts
import { Component, ElementRef, inject, signal, ViewChild } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { LucideAngularModule } from 'lucide-angular';
import { AuthService } from '../../core/auth/auth.service';
import { ComingSoonService } from '../../core/coming-soon/coming-soon.service';

/**
 * Storefront chrome: announcement bar + sticky navbar (Krypton brand).
 * Replaces the placeholder dark/magenta navbar. Keeps the auth-aware behaviour
 * (login/register vs. user + logout). The search reveals an animated input;
 * Enter navigates to /catalogo?q=term (the catalog reads it and filters by name).
 */
@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, LucideAngularModule],
  styles: [`
    :host { display: block; }
    lucide-icon { display: inline-flex; align-items: center; }
    .ann { display:flex; align-items:center; justify-content:center; gap:10px; height:40px;
           background:linear-gradient(90deg, var(--kr-orange-500), var(--kr-redorange-500));
           color:#fff; font-size:13.5px; font-weight:600; padding:0 16px; text-align:center; }
    .bar { position:sticky; top:0; z-index:40; }
    .nav { display:flex; align-items:center; justify-content:space-between; gap:24px; height:68px;
           padding:0 32px; background:rgba(255,255,255,0.92); backdrop-filter:blur(12px);
           border-bottom:1px solid var(--border-subtle); }
    .nav__logo { height:28px; width:auto; display:block; }
    .links { display:flex; align-items:center; gap:30px; }
    .link { position:relative; font-size:14.5px; font-weight:600; color:var(--text-body); text-decoration:none; cursor:pointer; background:none; border:none; font-family:var(--font-sans); padding:0; }
    .link::after { content:''; position:absolute; left:0; right:0; bottom:-6px; height:2px; background:var(--kr-blue-500);
                   border-radius:2px; transform:scaleX(0); transform-origin:left; transition:transform 200ms var(--ease-out); }
    .link:hover::after { transform:scaleX(1); }
    .link:hover { color:var(--kr-navy-800); }
    .actions { display:flex; align-items:center; gap:14px; }
    .icon-btn { display:inline-flex; align-items:center; justify-content:center; width:42px; height:42px; flex:none;
                border:1px solid var(--border-subtle); border-radius:12px; background:#fff; color:var(--kr-navy-800);
                cursor:pointer; text-decoration:none; transition:background 160ms ease, color 160ms ease; }
    .icon-btn--active { background:var(--kr-navy-800); color:#fff; }
    .search { width:250px; height:42px; flex:none; box-sizing:border-box; padding:0 16px; border:1.5px solid var(--border-subtle);
              border-radius:12px; background:var(--kr-gray-50); font-family:var(--font-sans); font-size:14.5px;
              color:var(--text-strong); outline:none; transform-origin:right center; }
    .search:focus { border-color:var(--kr-blue-600); background:#fff; box-shadow:0 0 0 3px rgba(26,125,215,0.16); }
    .login { font-size:14.5px; font-weight:600; color:var(--kr-navy-800); text-decoration:none; padding:0 6px; cursor:pointer;
             background:none; border:none; font-family:var(--font-sans); }
    .cta { display:inline-flex; align-items:center; height:42px; padding:0 20px; border-radius:999px;
           background:var(--kr-orange-500); color:#fff; font-size:14px; font-weight:700; text-decoration:none;
           box-shadow:0 10px 24px -10px rgba(243,116,2,0.6); transition:filter 120ms ease, box-shadow 200ms ease, transform 120ms ease; }
    .cta:hover { filter:brightness(0.96); box-shadow:0 18px 40px -10px rgba(243,116,2,0.72); }
    .cta:active { transform:scale(0.985); }
    .user { font-size:13.5px; color:var(--text-muted); max-width:180px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
  `],
  template: `
    <div class="ann">
      <lucide-icon name="truck" [size]="16"></lucide-icon>
      Envío gratis en compras desde S/ 199 — solo esta semana
    </div>

    <div class="bar">
      <header class="nav">
        <a routerLink="/" aria-label="Krypton inicio"><img class="nav__logo" src="/brand/Krypton-navy.svg" alt="Krypton"></a>

        @if (!searchOpen()) {
          <nav class="links">
            <a routerLink="/catalogo" class="link">Catálogo</a>
            <a routerLink="/catalogo" class="link">Categorías</a>
            <button type="button" class="link" (click)="comingSoon.show('Ofertas')">Ofertas</button>
            @if (auth.isAuthenticated()) { <a routerLink="/pedidos" class="link">Mis pedidos</a> }
          </nav>
        }

        <div class="actions">
          @if (searchOpen()) {
            <input #search class="search" [value]="query()" (input)="query.set($any($event.target).value)"
                   (keydown)="onKey($event)" placeholder="Buscar productos por nombre…">
          }
          <button class="icon-btn" [class.icon-btn--active]="searchOpen()" (click)="toggleSearch()" aria-label="Buscar">
            @if (!searchOpen()) {
              <svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
            } @else {
              <svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
            }
          </button>

          <a routerLink="/carrito" class="icon-btn" aria-label="Carrito">
            <lucide-icon name="shopping-cart" [size]="19"></lucide-icon>
          </a>

          @if (!auth.isAuthenticated()) {
            <a routerLink="/cuenta/ingresar" class="login">Iniciar sesión</a>
            <a routerLink="/cuenta/registro" class="cta">Crear cuenta</a>
          } @else {
            <span class="user">{{ auth.currentUser()?.email }}</span>
            @if (auth.isAdmin()) { <a routerLink="/admin" class="link">Admin</a> }
            <button class="login nav__logout" (click)="auth.logout()">Cerrar sesión</button>
          }
        </div>
      </header>
    </div>
  `,
})
export class NavbarComponent {
  protected readonly auth = inject(AuthService);
  protected readonly comingSoon = inject(ComingSoonService);
  private readonly router = inject(Router);

  readonly searchOpen = signal(false);
  readonly query = signal('');

  @ViewChild('search') searchInput?: ElementRef<HTMLInputElement>;

  toggleSearch(): void {
    const next = !this.searchOpen();
    this.searchOpen.set(next);
    if (next) {
      // wait for @if to render the input, then focus + animate it open
      setTimeout(() => {
        const el = this.searchInput?.nativeElement;
        if (!el) return;
        el.focus();
        el.animate(
          [{ transform: 'scaleX(0.25)', opacity: 0.35 }, { transform: 'scaleX(1)', opacity: 1 }],
          { duration: 300, easing: 'cubic-bezier(0.22,1,0.36,1)' },
        );
      });
    }
  }

  onKey(e: KeyboardEvent): void {
    if (e.key === 'Escape') this.searchOpen.set(false);
    if (e.key === 'Enter') this.submitSearch();
  }

  /** Navigate to the catalog with the search term; the catalog filters by name. */
  submitSearch(): void {
    const q = this.query().trim();
    this.router.navigate(['/catalogo'], { queryParams: q ? { q } : {} });
    this.searchOpen.set(false);
  }
}
