// frontend/src/app/features/home/home.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { LucideAngularModule } from 'lucide-angular';
import { ProductService } from '../catalog/product.service';
import { ComingSoonService } from '../../core/coming-soon/coming-soon.service';
import { ProductResponse, PLACEHOLDER_IMAGE } from '../../models/product.model';

interface Cat { name: string; icon: string; }
interface Perk { icon: string; title: string; desc: string; }

/**
 * Home / landing (Krypton). Renders INSIDE MainLayout (brand navbar + footer).
 * Featured products are REAL data (ProductService.featured); categories/perks/
 * promo are curated marketing content. Icons use lucide-angular.
 */
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterLink, LucideAngularModule],
  styles: [`
    :host { display:block; font-family:var(--font-sans); color:var(--text-strong); background:#eef1f6; }
    lucide-icon { display:inline-flex; align-items:center; }
    .wrap { max-width:1200px; margin:0 auto; padding:0 32px; }
    .eyebrow { font-size:12px; font-weight:700; letter-spacing:0.14em; text-transform:uppercase; color:var(--kr-blue-600); }
    .sec-head { display:flex; align-items:flex-end; justify-content:space-between; gap:16px; margin-bottom:28px; }
    .sec-title { font-family:var(--font-display); font-weight:800; font-size:34px; letter-spacing:-0.02em; color:var(--text-strong); margin:8px 0 0; }
    .see-all { font-size:14.5px; font-weight:700; color:var(--text-link); text-decoration:none; white-space:nowrap; }
    .muted { color:var(--text-muted); font-size:15px; }

    /* hero */
    .hero { position:relative; overflow:hidden; background:radial-gradient(130% 120% at 82% -10%, #0a3a7a 0%, #03275a 46%, #021a3d 100%); }
    .hero__img { position:absolute; inset:0; width:100%; height:100%; object-fit:cover; mix-blend-mode:multiply; opacity:0.5; pointer-events:none; }
    .hero__tint { position:absolute; inset:0; background:rgba(2,18,55,0.42); pointer-events:none; }
    .orb { position:absolute; border-radius:50%; filter:blur(8px); pointer-events:none; }
    .hero__inner { position:relative; z-index:2; max-width:1200px; margin:0 auto; padding:88px 32px 96px; }
    .hero__content { max-width:620px; color:#fff; }
    .hero__content > * { animation:krRise 620ms var(--ease-out) both; }
    .hero__content > *:nth-child(2){ animation-delay:90ms; }
    .hero__content > *:nth-child(3){ animation-delay:170ms; }
    .hero__content > *:nth-child(4){ animation-delay:250ms; }
    .hero__content > *:nth-child(5){ animation-delay:330ms; }
    .hero__eyebrow { display:inline-flex; align-items:center; gap:8px; font-size:12px; font-weight:700; letter-spacing:0.16em; text-transform:uppercase; color:var(--kr-blue-500); margin-bottom:22px; }
    .hero__title { color:#fff; font-family:var(--font-display); font-weight:900; font-style:italic; font-size:68px; line-height:0.96; letter-spacing:-0.028em; margin:0 0 22px; text-shadow:0 2px 28px rgba(2,18,55,0.5); }
    .hero__title .accent { color:var(--kr-orange-500); }
    .hero__sub { font-size:18px; line-height:1.6; color:rgba(255,255,255,0.72); margin:0 0 36px; max-width:480px; }
    .hero__ctas { display:flex; gap:14px; flex-wrap:wrap; }
    .hero__stats { display:flex; gap:30px; margin-top:44px; flex-wrap:wrap; }
    .stat-num { font-family:var(--font-display); font-weight:800; font-size:26px; color:#fff; }
    .stat-lbl { font-size:13px; color:rgba(255,255,255,0.6); }
    .stat-div { width:1px; background:rgba(255,255,255,0.18); }

    .cta-pri { display:inline-flex; align-items:center; gap:10px; height:56px; padding:0 28px; border:none; border-radius:999px;
               background:linear-gradient(120deg, var(--kr-orange-500), var(--kr-redorange-500)); color:#fff; font-size:16px;
               font-weight:700; font-family:var(--font-sans); cursor:pointer; text-decoration:none; box-shadow:0 16px 36px -10px rgba(243,116,2,0.62);
               transition:filter 120ms ease, box-shadow 200ms ease, transform 120ms ease; }
    .cta-pri:hover { filter:brightness(0.96); box-shadow:0 18px 40px -10px rgba(243,116,2,0.72); }
    .cta-pri:active { transform:scale(0.985); }
    .ghost { display:inline-flex; align-items:center; gap:9px; height:56px; padding:0 26px; border-radius:999px;
             background:rgba(255,255,255,0.06); border:1px solid rgba(255,255,255,0.28); color:#fff; font-size:16px;
             font-weight:600; font-family:var(--font-sans); cursor:pointer; text-decoration:none; transition:background 160ms ease, border-color 160ms ease; }
    .ghost:hover { background:rgba(255,255,255,0.12); border-color:rgba(255,255,255,0.5); }

    /* categories */
    .cat-grid { display:grid; grid-template-columns:repeat(6, 1fr); gap:16px; }
    .cat { display:flex; flex-direction:column; align-items:center; gap:14px; padding:26px 14px; background:#fff;
           border:1px solid var(--border-subtle); border-radius:18px; text-decoration:none;
           transition:transform 200ms var(--ease-out), box-shadow 200ms ease, border-color 200ms ease; }
    .cat:hover { transform:translateY(-4px); box-shadow:0 18px 36px -16px rgba(3,39,90,0.32); border-color:var(--kr-blue-500); }
    .cat__ic { display:inline-flex; align-items:center; justify-content:center; width:58px; height:58px; border-radius:16px;
               background:var(--kr-gray-100); color:var(--kr-navy-800); transition:background 200ms ease, color 200ms ease; }
    .cat:hover .cat__ic { background:var(--kr-blue-600); color:#fff; }
    .cat__name { font-size:14.5px; font-weight:700; color:var(--text-strong); }

    /* products */
    .prod-grid { display:grid; grid-template-columns:repeat(4, 1fr); gap:22px; }
    .card { display:flex; flex-direction:column; background:#fff; border:1px solid var(--border-subtle); border-radius:12px;
            overflow:hidden; transition:box-shadow 200ms var(--ease-out), transform 200ms var(--ease-out), border-color 200ms var(--ease-out); }
    .card:hover { box-shadow:0 18px 36px -18px rgba(3,39,90,0.3); transform:translateY(-3px); border-color:var(--kr-blue-500); }
    .card__media { position:relative; aspect-ratio:1/1; display:flex; align-items:center; justify-content:center; overflow:hidden;
                   background:linear-gradient(160deg, var(--kr-gray-50), #e7f0fb); }
    .card__media img { width:100%; height:100%; object-fit:contain; padding:16px; box-sizing:border-box; }
    .card__body { padding:16px; display:flex; flex-direction:column; gap:8px; flex:1; }
    .card__cat { font-size:11px; font-weight:700; letter-spacing:0.1em; text-transform:uppercase; color:var(--kr-blue-600); }
    .card__name-link { text-decoration:none; }
    .card__name { margin:0; font-size:15px; font-weight:600; color:var(--text-strong); line-height:1.3;
                  display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical; overflow:hidden; min-height:39px; }
    .card__foot { margin-top:auto; display:flex; align-items:flex-end; justify-content:space-between; gap:8px; padding-top:6px; }
    .card__price { font-size:19px; font-weight:800; color:var(--text-strong); letter-spacing:-0.01em; }
    .card__add { width:40px; height:40px; flex:none; display:inline-flex; align-items:center; justify-content:center; border-radius:10px;
                 border:none; cursor:pointer; background:var(--kr-orange-500); color:#fff; box-shadow:0 10px 20px -8px rgba(243,116,2,0.6);
                 transition:transform 120ms ease, filter 120ms ease; }
    .card__add:hover { filter:brightness(0.96); transform:scale(1.06); }

    /* promo */
    .promo { position:relative; overflow:hidden; border-radius:28px; background:radial-gradient(120% 160% at 12% 10%, #0a3a7a 0%, #03275a 50%, #021a3d 100%);
             padding:54px 56px; display:flex; align-items:center; justify-content:space-between; gap:32px; flex-wrap:wrap; }
    .promo__eyebrow { display:inline-flex; align-items:center; gap:8px; font-size:12px; font-weight:700; letter-spacing:0.14em;
                      text-transform:uppercase; color:var(--kr-yellow-500); margin-bottom:16px; }
    .promo__title { font-family:var(--font-display); font-weight:900; font-style:italic; font-size:40px; line-height:1.02;
                    letter-spacing:-0.025em; margin:0 0 14px; color:#fff; }
    .promo__title .accent { color:var(--kr-orange-500); }
    .promo__sub { font-size:16px; color:rgba(255,255,255,0.7); margin:0; max-width:460px; }

    /* trust */
    .trust-grid { display:grid; grid-template-columns:repeat(4, 1fr); gap:20px; }
    .perk { display:flex; align-items:center; gap:14px; padding:22px; background:#fff; border:1px solid var(--border-subtle); border-radius:16px; }
    .perk__ic { display:inline-flex; align-items:center; justify-content:center; width:48px; height:48px; flex:none; border-radius:13px;
                background:var(--kr-gray-100); color:var(--kr-blue-600); }
    .perk__title { font-size:15px; font-weight:700; color:var(--text-strong); }
    .perk__desc { font-size:13px; color:var(--text-muted); margin-top:2px; }

    @media (max-width:980px){ .cat-grid { grid-template-columns:repeat(3,1fr); } .prod-grid, .trust-grid { grid-template-columns:repeat(2,1fr); } .hero__title { font-size:48px; } }

    @keyframes krFloat  { 0%,100% { transform: translate(0,0); } 50% { transform: translate(0,-26px); } }
    @keyframes krFloat2 { 0%,100% { transform: translate(0,0); } 50% { transform: translate(0, 22px); } }
    @keyframes krRise   { from { opacity:0; transform: translateY(16px); } to { opacity:1; transform: translateY(0); } }
    @media (prefers-reduced-motion: reduce){ .hero__content > *, .orb { animation: none !important; } }
  `],
  template: `
    <!-- HERO -->
    <section class="hero">
      <img class="hero__img" src="/bg-login.webp" alt="">
      <div class="hero__tint"></div>
      <div class="orb" style="top:-160px; right:-120px; width:520px; height:520px; background:radial-gradient(circle, rgba(243,116,2,0.34), rgba(3,39,90,0) 64%); animation:krFloat 12s ease-in-out infinite;"></div>
      <div class="orb" style="bottom:-200px; left:-120px; width:540px; height:540px; background:radial-gradient(circle, rgba(26,125,215,0.40), rgba(3,39,90,0) 66%); animation:krFloat2 14s ease-in-out infinite;"></div>
      <div class="hero__inner">
        <div class="hero__content">
          <span class="hero__eyebrow"><lucide-icon name="zap" [size]="15" style="color:var(--kr-yellow-500);"></lucide-icon> Nueva temporada tech</span>
          <h1 class="hero__title"><span>Tecnología<br>que&ngsp;</span><span class="accent">enciende.</span></h1>
          <p class="hero__sub">Laptops, componentes y audio de última generación. Arma tu setup con lo mejor de la tecnología — envíos a todo el Perú en 24 horas.</p>
          <div class="hero__ctas">
            <a routerLink="/catalogo" class="cta-pri">Explorar el catálogo <lucide-icon name="arrow-right" [size]="20"></lucide-icon></a>
            <button type="button" class="ghost" (click)="comingSoon.show('Ofertas')"><lucide-icon name="tag" [size]="19" style="color:var(--kr-yellow-500);"></lucide-icon> Ver ofertas</button>
          </div>
          <div class="hero__stats">
            <div><div class="stat-num">+1,200</div><div class="stat-lbl">productos en stock</div></div>
            <div class="stat-div"></div>
            <div><div class="stat-num">24h</div><div class="stat-lbl">entrega express</div></div>
            <div class="stat-div"></div>
            <div><div class="stat-num" style="display:inline-flex;align-items:baseline;">4.8<span style="margin-left:5px;color:var(--kr-yellow-500);">★</span></div><div class="stat-lbl">valoración media</div></div>
          </div>
        </div>
      </div>
    </section>

    <!-- CATEGORIES -->
    <section class="wrap" style="padding-top:64px; padding-bottom:8px;">
      <div class="sec-head">
        <div><span class="eyebrow">Explora por categoría</span><h2 class="sec-title">¿Qué estás armando hoy?</h2></div>
        <a routerLink="/catalogo" class="see-all">Ver todo →</a>
      </div>
      <div class="cat-grid">
        @for (cat of categories; track cat.name) {
          <a routerLink="/catalogo" class="cat">
            <span class="cat__ic"><lucide-icon [name]="cat.icon" [size]="26"></lucide-icon></span>
            <span class="cat__name">{{ cat.name }}</span>
          </a>
        }
      </div>
    </section>

    <!-- FEATURED (real data) -->
    <section class="wrap" style="padding-top:56px; padding-bottom:8px;">
      <div class="sec-head">
        <div><span class="eyebrow">Lo más nuevo</span><h2 class="sec-title">Destacados del catálogo</h2></div>
        <a routerLink="/catalogo" class="see-all">Ver catálogo completo →</a>
      </div>

      @if (loadingProducts()) {
        <p class="muted">Cargando destacados…</p>
      } @else if (products().length === 0) {
        <p class="muted">Aún no hay productos para mostrar.</p>
      } @else {
        <div class="prod-grid">
          @for (p of products(); track p.id) {
            <article class="card">
              <a [routerLink]="['/catalogo', p.id]" class="card__media">
                <img [src]="p.imageUrl ?? PLACEHOLDER_IMAGE" [alt]="p.name">
              </a>
              <div class="card__body">
                <span class="card__cat">{{ p.categoryName }}</span>
                <a [routerLink]="['/catalogo', p.id]" class="card__name-link"><h3 class="card__name">{{ p.name }}</h3></a>
                <div class="card__foot">
                  <span class="card__price">{{ p.price | currency:'PEN':'symbol':'1.2-2' }}</span>
                  <button class="card__add" type="button" aria-label="Agregar al carrito" (click)="comingSoon.show('Carrito')">
                    <lucide-icon name="shopping-cart" [size]="18"></lucide-icon>
                  </button>
                </div>
              </div>
            </article>
          }
        </div>
      }
    </section>

    <!-- PROMO -->
    <section class="wrap" style="margin-top:64px;">
      <div class="promo">
        <div class="orb" style="top:-120px; right:14%; width:340px; height:340px; background:radial-gradient(circle, rgba(242,184,9,0.22), rgba(3,39,90,0) 70%); animation:krFloat 13s ease-in-out infinite;"></div>
        <div style="position:relative; z-index:2; color:#fff; max-width:560px;">
          <span class="promo__eyebrow"><lucide-icon name="percent" [size]="15"></lucide-icon> Oferta de temporada</span>
          <h2 class="promo__title">Hasta <span class="accent">30% de dscto.</span> en setups gamer</h2>
          <p class="promo__sub">Arma tu rig completo: GPU, monitor, periféricos y audio con descuentos exclusivos por tiempo limitado.</p>
        </div>
        <button type="button" class="cta-pri" style="position:relative; z-index:2; height:58px;" (click)="comingSoon.show('Ofertas')">Aprovechar ofertas <lucide-icon name="arrow-right" [size]="20"></lucide-icon></button>
      </div>
    </section>

    <!-- TRUST -->
    <section class="wrap" style="padding-top:64px; padding-bottom:72px;">
      <div class="trust-grid">
        @for (perk of perks; track perk.title) {
          <div class="perk">
            <span class="perk__ic"><lucide-icon [name]="perk.icon" [size]="23"></lucide-icon></span>
            <div><div class="perk__title">{{ perk.title }}</div><div class="perk__desc">{{ perk.desc }}</div></div>
          </div>
        }
      </div>
    </section>
  `,
})
export class HomeComponent implements OnInit {
  private readonly productService = inject(ProductService);
  protected readonly comingSoon = inject(ComingSoonService);

  protected readonly PLACEHOLDER_IMAGE = PLACEHOLDER_IMAGE;

  readonly products = signal<ProductResponse[]>([]);
  readonly loadingProducts = signal(true);

  // Curated visual shortcuts (navigate to the catalog). Not backend categories.
  readonly categories: Cat[] = [
    { name: 'Laptops', icon: 'laptop' },
    { name: 'Componentes', icon: 'cpu' },
    { name: 'Audio', icon: 'headphones' },
    { name: 'Monitores', icon: 'monitor' },
    { name: 'Periféricos', icon: 'keyboard' },
    { name: 'Gaming', icon: 'gamepad-2' },
  ];

  readonly perks: Perk[] = [
    { icon: 'truck', title: 'Envío en 24h', desc: 'Entrega express a todo el Perú' },
    { icon: 'shield-check', title: 'Pago seguro', desc: 'Transacciones 100% protegidas' },
    { icon: 'badge-check', title: 'Garantía oficial', desc: 'Productos con respaldo de marca' },
    { icon: 'rotate-ccw', title: 'Devoluciones', desc: '30 días para cambios y reembolsos' },
  ];

  ngOnInit(): void {
    this.productService.featured(4).subscribe({
      next: (ps) => {
        this.products.set(ps);
        this.loadingProducts.set(false);
      },
      error: () => {
        this.loadingProducts.set(false);
      },
    });
  }
}

// .claude/skills/krypton-design/ui_kits/storefront/Home.jsx
// Krypton storefront — Home screen.
function KrHome({ onNavigate, onAdd, onOpenProduct }) {
  const { Button, ProductCard, Badge } = window.KryptonDesignSystem_457463;
  const { products, categories } = window.KR_DATA;
  const featured = products.slice(0, 4);
  const deals = products.filter((p) => p.oldPrice).slice(0, 4);

  return (
    <div>
      {/* HERO — navy band */}
      <section style={{ background: "var(--surface-inverse)", color: "#fff", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", right: -120, top: -80, width: 460, height: 460, borderRadius: "50%",
          background: "radial-gradient(circle, rgba(26,125,215,0.55), transparent 65%)" }} />
        <div style={{ position: "absolute", right: 120, bottom: -160, width: 380, height: 380, borderRadius: "50%",
          background: "radial-gradient(circle, rgba(243,116,2,0.35), transparent 65%)" }} />
        <div style={{ maxWidth: "var(--container-max)", margin: "0 auto", padding: "72px 28px", position: "relative",
          display: "grid", gridTemplateColumns: "1.1fr 0.9fr", gap: 40, alignItems: "center" }}>
          <div>
            <span style={{ display: "inline-flex", alignItems: "center", gap: 8, fontSize: 12, fontWeight: 700,
              letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--kr-yellow-500)", marginBottom: 18 }}>
              <i data-lucide="zap" style={{ width: 15, height: 15 }} /> Tecnología de última generación
            </span>
            <h1 style={{ fontSize: 60, fontWeight: 900, fontStyle: "italic", lineHeight: 0.98, letterSpacing: "-0.02em", color: "#fff", margin: "0 0 18px" }}>
              Tecnología<br />que <span style={{ color: "var(--kr-orange-500)" }}>enciende</span>
            </h1>
            <p style={{ fontSize: 18, color: "var(--kr-gray-300)", maxWidth: 440, margin: "0 0 28px", lineHeight: 1.55 }}>
              Dispositivos y componentes para armar tu setup ideal. Envío a todo el Perú y garantía oficial.
            </p>
            <div style={{ display: "flex", gap: 12 }}>
              <Button variant="cta" size="lg" iconRight={<i data-lucide="arrow-right" style={{ width: 18, height: 18 }} />} onClick={() => onNavigate({ name: "catalog" })}>Explorar catálogo</Button>
              <Button variant="secondary" size="lg" style={{ background: "transparent", color: "#fff", borderColor: "rgba(255,255,255,0.3)" }} onClick={() => onNavigate({ name: "catalog", category: "Gaming" })}>Ver ofertas</Button>
            </div>
            <div style={{ display: "flex", gap: 28, marginTop: 36 }}>
              {[["truck", "Envío gratis", "desde S/ 199"], ["shield-check", "Garantía", "oficial 12 meses"], ["credit-card", "Cuotas", "sin interés"]].map(([ic, t, s]) => (
                <div key={t} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <i data-lucide={ic} style={{ width: 22, height: 22, color: "var(--kr-blue-500)" }} />
                  <div style={{ lineHeight: 1.2 }}>
                    <div style={{ fontSize: 14, fontWeight: 600, color: "#fff" }}>{t}</div>
                    <div style={{ fontSize: 12, color: "var(--kr-gray-400)" }}>{s}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
          {/* Hero product tile */}
          <div style={{ display: "flex", justifyContent: "center" }}>
            <div style={{ width: 320, height: 320, borderRadius: 28, background: "linear-gradient(160deg, rgba(255,255,255,0.10), rgba(255,255,255,0.02))",
              border: "1px solid rgba(255,255,255,0.14)", display: "flex", alignItems: "center", justifyContent: "center", position: "relative", boxShadow: "var(--shadow-lg)" }}>
              <i data-lucide="laptop" style={{ width: 150, height: 150, color: "#fff", strokeWidth: 1 }} />
              <span style={{ position: "absolute", top: 18, left: 18 }}><Badge tone="cta" solid>Más vendido</Badge></span>
              <div style={{ position: "absolute", bottom: 18, left: 18, right: 18, background: "rgba(255,255,255,0.95)", borderRadius: 14, padding: "12px 14px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text-strong)" }}>UltraBook 14" i7</div>
                <div style={{ fontSize: 17, fontWeight: 800, color: "var(--text-strong)" }}>S/ 4,299</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <div style={{ maxWidth: "var(--container-max)", margin: "0 auto", padding: "0 28px" }}>
        {/* Categories */}
        <section style={{ marginTop: 44 }}>
          <h2 style={{ fontSize: 24, fontWeight: 800, color: "var(--text-strong)", margin: "0 0 18px" }}>Compra por categoría</h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(8, 1fr)", gap: 12 }}>
            {categories.map((c) => (
              <button key={c.name} onClick={() => onNavigate({ name: "catalog", category: c.name })}
                style={{ background: "var(--surface-card)", border: "1px solid var(--border-subtle)", borderRadius: 14,
                  padding: "18px 8px", display: "flex", flexDirection: "column", alignItems: "center", gap: 10, cursor: "pointer",
                  fontFamily: "var(--font-sans)", transition: "all var(--dur-base) var(--ease-out)" }}
                onMouseEnter={(e) => { e.currentTarget.style.borderColor = "var(--kr-blue-100)"; e.currentTarget.style.boxShadow = "var(--shadow-sm)"; e.currentTarget.style.transform = "translateY(-2px)"; }}
                onMouseLeave={(e) => { e.currentTarget.style.borderColor = "var(--border-subtle)"; e.currentTarget.style.boxShadow = "none"; e.currentTarget.style.transform = "none"; }}>
                <span style={{ width: 46, height: 46, borderRadius: 12, background: "var(--kr-blue-50)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                  <i data-lucide={c.icon} style={{ width: 22, height: 22, color: "var(--color-brand)" }} />
                </span>
                <span style={{ fontSize: 12.5, fontWeight: 600, color: "var(--text-strong)", textAlign: "center" }}>{c.name}</span>
              </button>
            ))}
          </div>
        </section>

        {/* Featured */}
        <Section title="Destacados" action="Ver todo" onAction={() => onNavigate({ name: "catalog" })}>
          {featured.map((p) => (
            <ProductCard key={p.id} {...p} onAdd={() => onAdd(p)} onClick={() => onOpenProduct(p)} />
          ))}
        </Section>

        {/* Feature band */}
        <section style={{ marginTop: 48, background: "linear-gradient(110deg, var(--kr-orange-500), var(--kr-redorange-500))",
          borderRadius: 24, padding: "36px 40px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 24, color: "#fff", boxShadow: "var(--shadow-cta)" }}>
          <div>
            <div style={{ fontSize: 12, fontWeight: 700, letterSpacing: "0.14em", textTransform: "uppercase", opacity: 0.9 }}>Krypton Days</div>
            <h2 style={{ fontSize: 34, fontWeight: 900, fontStyle: "italic", color: "#fff", margin: "8px 0 6px" }}>Hasta 20% en gaming</h2>
            <p style={{ margin: 0, fontSize: 16, opacity: 0.92 }}>Mouse, teclados, controles y más. Por tiempo limitado.</p>
          </div>
          <Button variant="secondary" size="lg" style={{ background: "#fff", color: "var(--kr-redorange-600)", borderColor: "#fff" }} onClick={() => onNavigate({ name: "catalog", category: "Gaming" })}>Ver ofertas</Button>
        </section>

        {/* Deals */}
        <Section title="Ofertas de la semana" action="Ver todo" onAction={() => onNavigate({ name: "catalog" })}>
          {deals.map((p) => (
            <ProductCard key={p.id} {...p} onAdd={() => onAdd(p)} onClick={() => onOpenProduct(p)} />
          ))}
        </Section>
      </div>
    </div>
  );
}

function Section({ title, action, onAction, children }) {
  return (
    <section style={{ marginTop: 48 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }}>
        <h2 style={{ fontSize: 24, fontWeight: 800, color: "var(--text-strong)", margin: 0 }}>{title}</h2>
        {action && <button onClick={onAction} style={{ background: "none", border: "none", cursor: "pointer", color: "var(--color-brand)", fontFamily: "var(--font-sans)", fontWeight: 600, fontSize: 14, display: "inline-flex", alignItems: "center", gap: 4 }}>{action} <i data-lucide="chevron-right" style={{ width: 16, height: 16 }} /></button>}
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 18 }}>{children}</div>
    </section>
  );
}
window.KrHome = KrHome;
